nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market NVDA_NASDAQ  > NVDA_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market AMZN_NASDAQ  > AMZN_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market META_NASDAQ  > META_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market SNOW_NYSE  > SNOW_NYSE_find_ermai_ML.log 2>&1 &

nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market U_NYSE  > U_NYSE_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market AVGO_NASDAQ  > AVGO_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market NVO_NYSE  > NVO_NYSE_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market ADBE_NASDAQ  > ADBE_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market TSM_NYSE  > TSM_NYSE_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market JPM_NYSE  > JPM_NYSE_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market BAC_NYSE  > BAC_NYSE_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market COST_NASDAQ  > COST_NASDAQ_find_ermai_ML.log 2>&1 &
nohup python -u find_ermai_penlevel_zhongshu_ML_for_visualization.py --print_process_info --info_save_to_file_mode --show_fig_when_sell_buy_action --group_size_for_high_level 1 --group_size_for_low_level 1 --stock_name_and_market NFLX_NASDAQ  > NFLX_NASDAQ_find_ermai_ML.log 2>&1 &
