All_STOCK_IN_LIST = ["NVDA_NASDAQ", "AMZN_NASDAQ", "META_NASDAQ", "MSFT_NASDAQ", "SNOW_NYSE", "TIGR_NASDAQ", "TSLA_NASDAQ", "U_NYSE", "AVGO_NASDAQ", "AAPL_NASDAQ",
 "LLY_NYSE", "NVO_NYSE", "ADBE_NASDAQ", "TSM_NYSE", "PFE_NYSE", "JPM_NYSE", "BAC_NYSE", "COST_NASDAQ", "NFLX_NASDAQ"]

STOCK_NAME_AND_MARKET = "NVDA_NASDAQ"